export default {
  ADD_BASKET: 'ADD_BASKET',
  REMOVE_BASKET: 'REMOVE_BASKET',
  DECREMENT_QTY: 'DECREMENT_QTY',
  INCREMENT_QTY: 'INCREMENT_QTY',
  UPDATE_BASKET_FROM_LOCALSTORAGE: 'UPDATE_BASKET_FROM_LOCALSTORAGE',
  UPDATE_BASKET_FROM_DB: 'UPDATE_BASKET_FROM_DB',
  RESET_LOCAL_BASKET: 'RESET_LOCAL_BASKET',
};
