export default {
  GET_STORE: 'GET_STORE',
  ADD_CATEGORY: 'ADD_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  ADD_BRAND: 'ADD_BRAND',
  UPDATE_BRAND: 'UPDATE_BRAND',
  REMOVE_BRAND: 'REMOVE_BRAND',
  UPDATE_SEARCH: 'UPDATE_SEARCH',
};
